apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'expo-module-gradle-plugin'

group = 'expo.modules.tezprinter'
version = '1.0.0'

def getExtOrDefault(name, defaultValue) {
  return rootProject.ext.has(name) ? rootProject.ext.get(name) : defaultValue
}

android {
  compileSdk getExtOrDefault('compileSdkVersion', 35)
  namespace "expo.modules.tezprinter"
  defaultConfig {
    minSdk getExtOrDefault('minSdkVersion', 24)
    targetSdk getExtOrDefault('targetSdkVersion', 35)
    versionCode 1
    versionName "1.0.0"
  }
  lintOptions {
    abortOnError false
  }
}

repositories {
  google()
  mavenCentral()
  flatDir {
    dirs 'libs'
  }
}

dependencies {
  implementation 'androidx.core:core-ktx:1.13.1'
  implementation files('libs/PrintSDK-68.aar')
}
