import type { MediaProfile } from '@/printing/document/types';

const DEFAULT_SAFE_AREA = { topMm: 1, rightMm: 1, bottomMm: 1, leftMm: 1 };

/** Predefined media profiles covering standard physical label stock. */
export const MEDIA_PROFILES: MediaProfile[] = [
  // Jewellery & cable specialty die-cuts
  {
    id: 'jewellery-tag-14x96',
    name: 'Jewellery tag 14 × 96 mm',
    type: 'diecut',
    widthMm: 14,
    heightMm: 96,
    gapMm: 3,
    shape: 'diecut',
    category: 'jewellery',
    columns: 1,
    safeAreaInset: { topMm: 1.5, rightMm: 1, bottomMm: 1.5, leftMm: 1 },
  },
  {
    id: 'jewellery-2up-37x96',
    name: 'Jewellery 2-up 37 × 96 mm',
    type: 'diecut',
    widthMm: 37,
    heightMm: 96,
    gapMm: 3,
    shape: 'diecut',
    category: 'jewellery',
    columns: 2,
    safeAreaInset: { topMm: 1.5, rightMm: 1, bottomMm: 1.5, leftMm: 1 },
  },
  {
    id: 'jewellery-3up-54x96',
    name: 'Jewellery 3-up 54 × 96 mm',
    type: 'diecut',
    widthMm: 54,
    heightMm: 96,
    gapMm: 3,
    shape: 'diecut',
    category: 'jewellery',
    columns: 3,
    safeAreaInset: { topMm: 1.5, rightMm: 1, bottomMm: 1.5, leftMm: 1 },
  },
  {
    id: 'jewellery-50x15',
    name: '50 × 15 mm Jewelry',
    type: 'gap',
    widthMm: 50,
    heightMm: 15,
    gapMm: 3,
    shape: 'rectangle',
    cornerRadiusMm: 1,
    category: 'jewellery',
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'jewellery-80x15-rat-tail',
    name: '80 × 15 mm Rat Tail Tag',
    type: 'diecut',
    widthMm: 80,
    heightMm: 15,
    gapMm: 3,
    shape: 'diecut',
    category: 'jewellery',
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'jewellery-85x13-barbell',
    name: '85 × 13 mm Barbell',
    type: 'diecut',
    widthMm: 85,
    heightMm: 13,
    gapMm: 3,
    shape: 'diecut',
    category: 'jewellery',
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'jewellery-85x15-barbell',
    name: '85 × 15 mm Barbell',
    type: 'diecut',
    widthMm: 85,
    heightMm: 15,
    gapMm: 3,
    shape: 'diecut',
    category: 'jewellery',
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'cable-flag-50x73',
    name: 'Cable label 50 × 73 mm',
    type: 'diecut',
    widthMm: 50,
    heightMm: 73,
    gapMm: 3,
    shape: 'diecut',
    category: 'cable',
    columns: 2,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'cable-flag-50x70',
    name: 'Cable label 50 × 73 mm',
    type: 'diecut',
    widthMm: 50,
    heightMm: 73,
    gapMm: 3,
    shape: 'diecut',
    category: 'cable',
    columns: 2,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'cable-flag-50x70-2up',
    name: 'Cable label 50 × 73 mm',
    type: 'diecut',
    widthMm: 50,
    heightMm: 73,
    gapMm: 3,
    shape: 'diecut',
    category: 'cable',
    columns: 2,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },

  // Standard retail, barcode & price tags
  {
    id: 'rect-20x15',
    name: '20 × 15 mm Tiny',
    type: 'gap',
    widthMm: 20,
    heightMm: 15,
    gapMm: 2,
    shape: 'rectangle',
    cornerRadiusMm: 1,
    safeAreaInset: { topMm: 0.8, rightMm: 0.8, bottomMm: 0.8, leftMm: 0.8 },
  },
  {
    id: 'rect-25x15',
    name: '25 × 15 mm Small',
    type: 'gap',
    widthMm: 25,
    heightMm: 15,
    gapMm: 2,
    shape: 'rectangle',
    cornerRadiusMm: 1,
    safeAreaInset: { topMm: 0.8, rightMm: 0.8, bottomMm: 0.8, leftMm: 0.8 },
  },
  {
    id: 'rect-30x20',
    name: '30 × 20 mm Mini',
    type: 'gap',
    widthMm: 30,
    heightMm: 20,
    gapMm: 2,
    shape: 'rectangle',
    cornerRadiusMm: 1.5,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'rect-40x30',
    name: '40 × 30 mm Price Tag',
    type: 'gap',
    widthMm: 40,
    heightMm: 30,
    gapMm: 3,
    shape: 'rectangle',
    cornerRadiusMm: 1.5,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'rect-50x25',
    name: '50 × 25 mm',
    type: 'gap',
    widthMm: 50,
    heightMm: 25,
    gapMm: 3,
    shape: 'rectangle',
    cornerRadiusMm: 1.5,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'rect-50x30',
    name: '50 × 30 mm Retail',
    type: 'gap',
    widthMm: 50,
    heightMm: 30,
    gapMm: 3,
    shape: 'rectangle',
    cornerRadiusMm: 1.5,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'rect-50x70',
    name: '50 × 70 mm',
    type: 'gap',
    widthMm: 50,
    heightMm: 70,
    gapMm: 3,
    shape: 'rectangle',
    cornerRadiusMm: 2,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'rect-57x30-receipt',
    name: '57 × 30 mm Receipt',
    type: 'continuous',
    widthMm: 57,
    heightMm: 30,
    gapMm: 0,
    shape: 'rectangle',
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'rect-60x40',
    name: '60 × 40 mm Barcode',
    type: 'gap',
    widthMm: 60,
    heightMm: 40,
    gapMm: 3,
    shape: 'rectangle',
    cornerRadiusMm: 2,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'rect-80x50',
    name: '80 × 50 mm',
    type: 'gap',
    widthMm: 80,
    heightMm: 50,
    gapMm: 3,
    shape: 'rectangle',
    cornerRadiusMm: 2,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },

  // Imperial & Courier sizes
  {
    id: 'rect-2x1in',
    name: '2 × 1 in (50.8 × 25.4 mm)',
    type: 'gap',
    widthMm: 50.8,
    heightMm: 25.4,
    gapMm: 3.175,
    shape: 'rectangle',
    cornerRadiusMm: 1.5,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'rect-3x2in',
    name: '3 × 2 in (76.2 × 50.8 mm)',
    type: 'gap',
    widthMm: 76.2,
    heightMm: 50.8,
    gapMm: 3.175,
    shape: 'rectangle',
    cornerRadiusMm: 2,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'rect-75x100',
    name: '75 × 100 mm (3 × 4 in)',
    type: 'gap',
    widthMm: 75,
    heightMm: 100,
    gapMm: 3,
    shape: 'rectangle',
    cornerRadiusMm: 2,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'rect-76x130',
    name: '76 × 130 mm Courier',
    type: 'gap',
    widthMm: 76,
    heightMm: 130,
    gapMm: 3,
    shape: 'rectangle',
    cornerRadiusMm: 2,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },

  // Shipping & Large format
  {
    id: 'rect-100x100',
    name: '100 × 100 mm (4 × 4 in)',
    type: 'gap',
    widthMm: 100,
    heightMm: 100,
    gapMm: 3,
    shape: 'rectangle',
    cornerRadiusMm: 2,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'shipping-100x150',
    name: '100 × 150 mm shipping',
    type: 'gap',
    widthMm: 100,
    heightMm: 150,
    gapMm: 3,
    shape: 'rectangle',
    cornerRadiusMm: 2,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'rect-100x155-waybill',
    name: '100 × 155 mm Waybill',
    type: 'gap',
    widthMm: 100,
    heightMm: 155,
    gapMm: 3,
    shape: 'rectangle',
    cornerRadiusMm: 2,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'shipping-4x6in',
    name: '4 × 6 in (101.6 × 152.4 mm)',
    type: 'gap',
    widthMm: 101.6,
    heightMm: 152.4,
    gapMm: 3.175,
    shape: 'rectangle',
    cornerRadiusMm: 2,
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
  {
    id: 'iso-a6',
    name: 'A6 (105 × 148 mm)',
    type: 'gap',
    widthMm: 105,
    heightMm: 148,
    gapMm: 3,
    shape: 'rectangle',
    safeAreaInset: DEFAULT_SAFE_AREA,
  },
];

export function mediaFromSize(
  widthMm: number,
  heightMm: number,
  extras?: Partial<MediaProfile>,
): MediaProfile {
  const named = MEDIA_PROFILES.find(
    (p) => Math.abs(p.widthMm - widthMm) < 0.2 && Math.abs(p.heightMm - heightMm) < 0.2,
  );
  if (named && !extras) return named;
  return {
    id: extras?.id ?? named?.id ?? `custom-${widthMm}x${heightMm}`,
    name: extras?.name ?? named?.name ?? `${widthMm} × ${heightMm} mm`,
    type: extras?.type ?? named?.type ?? 'gap',
    widthMm,
    heightMm,
    gapMm: extras?.gapMm ?? named?.gapMm ?? 3,
    blackMarkMm: extras?.blackMarkMm ?? named?.blackMarkMm,
    shape: extras?.shape ?? named?.shape ?? 'rectangle',
    category: extras?.category ?? named?.category,
    shapePath: extras?.shapePath ?? named?.shapePath,
    printableArea: extras?.printableArea ?? named?.printableArea,
    safeAreaInset:
      extras?.safeAreaInset ??
      named?.safeAreaInset ?? { topMm: 1, rightMm: 1, bottomMm: 1, leftMm: 1 },
    cornerRadiusMm: extras?.cornerRadiusMm ?? named?.cornerRadiusMm,
    columns: extras?.columns ?? named?.columns,
  };
}
